### ISSUE TITLE
Single process consumption exception, what is the cause?

### ISSUE THREAD

**Issue by twomiao** [xobotyi/beansclient#3]
```
while (true) {
    try {
        $job = $beansClient->watchTube('Order')
            ->reserve();
        $payload = $job->payload;
        if (!empty($payload))
        {
            var_dump($job->payload);
        }
    } catch (\Exception $ex) {
        var_dump($ex->getTraceAsString());
        var_dump($beansClient->getConnection()->isActive());
        exit;
    }
}
```

Backtrace:
```
string(406) "#0 /home/Serve/Resque/vendor/xobotyi/beansclient/src/BeansClient.php(122): xobotyi\beansclient\Command\Reserve->parseResponse(Array, NULL)
#1 /home/Serve/Resque/vendor/xobotyi/beansclient/src/BeansClient.php(304): xobotyi\beansclient\BeansClient->dispatchCommand(Object(xobotyi\beansclient\Command\Reserve))
#2 /home/Serve/Resque/app/test/stalk.php(24): xobotyi\beansclient\BeansClient->reserve()
#3 {main}"
bool(true)
```

**Comment by xobotyi** [comment]
What's the error message and code?

**Comment by twomiao** [comment]
> What's an exception message and code?

What is the meaning of this DEADLINE_SOON exception and how to resolve it?
### The test code:
```<?php
$connection = new Connection('127.0.0.1', 11300, 2, true);
$beansClient = new BeansClient($connection);

try {
    while (true) {
        $job = $beansClient->watchTube('Order')
            ->reserve(5)->payload;

        if (empty($job)) {
            var_dump($connection->isActive());
        }

        if ($job)
        {
            var_dump($job);
        }
    }
} catch (\Exception $e) {
    throw $e;
}
```

**Comment by xobotyi** [comment]
`DEADLINE_SOON` is a beanstalkd response.
>During the TTR of a reserved job, the last second is kept by the server as a
safety margin, during which the client will not be made to wait for another
job. If the client issues a reserve command during the safety margin, or if
the safety margin arrives while the client is waiting on a reserve command,
the server will respond with:
>
>    DEADLINE_SOON\r\n
